### ISSUE TITLE
[bug] Problem during HTML rendering : Empty space in place of the STL view

### ISSUE THREAD

**Issue by GentilsTo** [Peque/sphinxstl#2]
Hi,
was looking to try your module for sphinx as I'm interested to render STL in my doc.
Unfortunately, while trying to reproduce the examples you provided (or from a personal file) I only get an empty space in my build HTML. Is there any particular requirement for using this module ?
(I tried with python 2.7.16, Sphinx 1.8.5).

Thanks !

**Comment by Peque** [comment]
Unfortunately, only Python 3 is supported:

https://github.com/Peque/sphinxstl/blob/d40beecc931195746627ec46f3145f6c65655c59/setup.py#L27

I would advise you to switch all your projects to Python 3 as soon as possible, since [Python 2 is already end-of-life](https://www.python.org/doc/sunset-python-2/). :heart:

**Comment by GentilsTo** [comment]
Thanks for the quick reply, sorry not noticing it ! That indeed a good advice
